# Copyright © 2026, UChicago Argonne, LLC
# See LICENSE for terms and disclaimer.

"""Centralized data access and artifact management for Adapt pipeline.

Provides a unified API for:
- Registering artifacts with lineage tracking
- Writing NetCDF, Parquet, and SQLite data atomically
- Querying artifacts by type, time range, and radar
- Opening datasets and tables for analysis

The DataRepository is the single source of truth for all pipeline artifacts.
No other component should directly access the filesystem for data I/O.
"""

import hashlib
import json
import logging
import os
import shutil
import sqlite3
import tempfile
import threading
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Optional

import pandas as pd
import xarray as xr

from adapt.persistence.catalog import RadarCatalog
from adapt.persistence.registry import RepositoryRegistry

if TYPE_CHECKING:
    from adapt.configuration.schemas import InternalConfig

__all__ = ['DataRepository', 'ProductType']

logger = logging.getLogger(__name__)


class ProductType:
    """Artifact product type constants."""
    NEXRAD_RAW = "nexrad_raw"
    GRIDDED_NC = "gridded3d"  # Updated to match new catalog
    ANALYSIS_NC = "segmentation2d"  # Updated to match new catalog
    CELLS_DB = "cells_db"  # DEPRECATED - use ANALYSIS2D_PARQUET
    CELLS_PARQUET = "cells_parquet"  # DEPRECATED - use ANALYSIS2D_PARQUET
    ANALYSIS2D_PARQUET = "analysis2d"  # NEW: Standard name for analysis tables
    PLOT_PNG = "plot_png"


class DataRepository:
    """Centralized artifact management for radar processing pipeline.

    Manages the complete lifecycle of pipeline artifacts:
    - Registration in per-run SQLite catalog
    - Atomic file writes with lineage tracking
    - Processing status management
    - Query API for downstream consumers

    Directory Structure:
        root_dir/
        ├── catalog/{run_id}_pipeline_catalog.db
        ├── RADAR_ID/
        │   ├── nexrad/YYYYMMDD/{original_aws_name}
        │   ├── gridnc/YYYYMMDD/{file_stem}_{run_id}_gridded.nc
        │   ├── analysis/YYYYMMDD/{file_stem}_{run_id}_analysis.nc
        │   ├── analysis/YYYYMMDD/{radar}_{run_id}_cells.db
        │   └── plots/YYYYMMDD/{radar}_{plot_type}_{HHMMSS}_{run_id}.png
        └── logs/

    Thread Safety:
        All methods are thread-safe via internal locking.
        Multiple threads can register and query artifacts concurrently.

    Example usage::

        # Create repository for a pipeline run
        repo = DataRepository(
            run_id="abc12345",
            base_dir="/data/radar_output",
            radar="KDIX"
        )

        # Write gridded NetCDF with lineage
        gridded_id = repo.write_netcdf(
            ds=gridded_dataset,
            product_type=ProductType.GRIDDED_NC,
            scan_time=datetime(2026, 2, 11, 12, 0, 0),
            producer="loader",
            parent_ids=[raw_artifact_id],
            metadata={"grid_shape": [41, 201, 201]}
        )

        # Query artifacts
        grids = repo.query(product_type=ProductType.GRIDDED_NC)
    """

    def __init__(
        self,
        run_id: str,
        base_dir: str | Path,
        radar: str,
        config: Optional["InternalConfig"] = None,
    ):
        """Initialize repository for a pipeline run.

        Parameters
        ----------
        run_id : str
            Unique run identifier for this pipeline run.
            Generated by orchestrator at startup.
        base_dir : str or Path
            Root output directory for all artifacts.
        radar : str
            Radar station identifier (e.g., "KDIX").
        config : InternalConfig, optional
            Validated runtime configuration.
        """
        self.run_id = run_id
        self.base_dir = Path(base_dir).resolve()
        self.radar = radar
        self.config = config

        # Create directory structure FIRST (radar_catalog needs the dir to exist)
        self._init_directories()

        # Catalog system
        self.registry = RepositoryRegistry.get_instance(self.base_dir)
        self.catalog = RadarCatalog(self.base_dir / radar)

        # Thread safety
        self._lock = threading.RLock()

        # Register this run in catalog and registry
        self._register_in_new_catalog()

        logger.debug("DataRepository ready: run=%s radar=%s", run_id, radar)

    def _init_directories(self) -> None:
        """Create directory structure for this radar."""
        radar_base = self.base_dir / self.radar

        self.output_dirs = {
            "base": self.base_dir,
            "nexrad": radar_base / "nexrad",
            "gridnc": radar_base / "gridnc",
            "analysis": radar_base / "analysis",
            "plots": radar_base / "plots",
            "logs": self.base_dir / "logs",
        }

        for path in self.output_dirs.values():
            path.mkdir(parents=True, exist_ok=True)

    # =========================================================================
    # Catalog Registration
    # =========================================================================

    def _register_in_new_catalog(self) -> None:
        """Register this run in the new Registry and RadarCatalog system."""
        # Register radar in global registry (idempotent), including optional location metadata.
        radars = self.registry.list_radars()
        row = radars[radars["radar"] == self.radar] if not radars.empty else None
        existing_lat = row.iloc[0]["location_lat"] if row is not None and not row.empty else None
        existing_lon = row.iloc[0]["location_lon"] if row is not None and not row.empty else None

        # Do not use external lookup tables for location metadata. The pipeline
        # will populate location_lat/location_lon from the first ingested radar file.
        self.registry.register_radar(self.radar, lat=existing_lat, lon=existing_lon)
        
        # Save runtime config to radar directory first
        config_path = None
        if self.config:
            config_file = self.catalog.radar_dir / f"config_run_{self.run_id}.json"
            if not config_file.exists():
                config_json = self.config.model_dump_json()
                with open(config_file, 'w') as f:
                    f.write(config_json)
                logger.debug(f"Saved runtime config: {config_file}")
            config_path = str(config_file.relative_to(self.base_dir))
        
        # Register this run in global registry
        mode = self.config.mode if self.config else "unknown"
        
        self.registry.register_run(
            run_id=self.run_id,
            radar=self.radar,
            mode=mode,
            config_path=config_path,
            repository_version="0.1.0"
        )

    # =========================================================================
    # Artifact ID Generation
    # =========================================================================

    @staticmethod
    def generate_artifact_id(
        product_type: str,
        radar: str,
        scan_time: datetime | None,
        run_id: str,
        content_hint: str = ""
    ) -> str:
        """Generate deterministic artifact ID from content metadata.

        Parameters
        ----------
        product_type : str
            Type of artifact (e.g., ProductType.GRIDDED_NC)
        radar : str
            Radar station identifier
        scan_time : datetime or None
            Timestamp of radar scan
        run_id : str
            Pipeline run identifier
        content_hint : str, optional
            Additional content for uniqueness (e.g., file hash)

        Returns
        -------
        str
            16-character hash-based artifact ID
        """
        time_str = scan_time.isoformat() if scan_time else "none"
        content = f"{product_type}:{radar}:{time_str}:{run_id}:{content_hint}"
        return hashlib.sha256(content.encode()).hexdigest()[:16]

    # =========================================================================
    # Public API: Registration
    # =========================================================================

    def register_artifact(
        self,
        product_type: str,
        file_path: str | Path,
        scan_time: datetime | None = None,
        producer: str = "unknown",
        parent_ids: list[str] | None = None,
        metadata: dict | None = None
    ) -> str:
        """Register an artifact in the RadarCatalog.

        Parameters
        ----------
        product_type : str
            Artifact type (use ProductType constants)
        file_path : str or Path
            Absolute path to artifact file
        scan_time : datetime, optional
            Timestamp of radar scan
        producer : str
            Name of component that created this artifact
        parent_ids : list of str, optional
            Artifact IDs of parent artifacts (for lineage)
        metadata : dict, optional
            Additional metadata (stored as JSON)

        Returns
        -------
        str
            Unique artifact ID
        """
        file_path = Path(file_path).resolve()
        parent_ids = parent_ids or []
        metadata = metadata or {}

        artifact_id = self.generate_artifact_id(
            product_type=product_type,
            radar=self.radar,
            scan_time=scan_time,
            run_id=self.run_id,
            content_hint=str(file_path)
        )

        radar_dir = self.base_dir / self.radar
        try:
            relative_path = file_path.relative_to(radar_dir)
        except ValueError:
            relative_path = file_path

        file_size = file_path.stat().st_size if file_path.exists() else None

        catalog_metadata = metadata.copy()
        catalog_metadata['producer'] = producer

        self.catalog.register_item(
            item_id=artifact_id,
            run_id=self.run_id,
            item_type=product_type,
            scan_time=scan_time.isoformat() if scan_time else None,
            file_path=str(relative_path),
            parent_ids=parent_ids,
            metadata=catalog_metadata,
            file_size_bytes=file_size,
        )
        logger.debug("Registered artifact: %s (%s)", artifact_id, product_type)
        return artifact_id

    # =========================================================================
    # Public API: Data Access
    # =========================================================================

    def open_dataset(self, artifact_id: str) -> xr.Dataset:
        """Open NetCDF artifact as xarray Dataset.

        Parameters
        ----------
        artifact_id : str
            Artifact ID (must be NetCDF type)

        Returns
        -------
        xr.Dataset
            Opened dataset (caller responsible for closing)

        Raises
        ------
        ValueError
            If artifact not found or not a NetCDF type
        FileNotFoundError
            If file does not exist
        """
        artifact = self._get_artifact(artifact_id)

        if artifact is None:
            raise ValueError(f"Artifact not found: {artifact_id}")

        product_type = artifact['product_type']
        if product_type not in (ProductType.GRIDDED_NC, ProductType.ANALYSIS_NC):
            raise ValueError(f"Cannot open as dataset: {product_type}")

        file_path = Path(artifact['file_path'])
        if not file_path.exists():
            raise FileNotFoundError(f"File not found: {file_path}")

        return xr.open_dataset(file_path)

    def open_table(
        self,
        artifact_id: str,
        table_name: str | None = None
    ) -> pd.DataFrame:
        """Open SQLite or Parquet artifact as DataFrame.

        Parameters
        ----------
        artifact_id : str
            Artifact ID (must be CELLS_DB or CELLS_PARQUET type)
        table_name : str, optional
            Table name for SQLite (default: 'cells')

        Returns
        -------
        pd.DataFrame
            Data from artifact

        Raises
        ------
        ValueError
            If artifact not found or invalid type
        """
        artifact = self._get_artifact(artifact_id)

        if artifact is None:
            raise ValueError(f"Artifact not found: {artifact_id}")

        product_type = artifact['product_type']
        file_path = Path(artifact['file_path'])

        if not file_path.exists():
            raise FileNotFoundError(f"File not found: {file_path}")

        if product_type == ProductType.CELLS_PARQUET:
            return pd.read_parquet(file_path)
        elif product_type == ProductType.CELLS_DB:
            table_name = table_name or 'cells'
            with sqlite3.connect(str(file_path)) as conn:
                return pd.read_sql(f"SELECT * FROM {table_name}", conn)
        else:
            raise ValueError(f"Cannot open as table: {product_type}")

    def query(
        self,
        product_type: str | None = None,
        time_range: tuple[datetime, datetime] | None = None,
        radar: str | None = None,
        limit: int | None = None
    ) -> list[dict]:
        """Query artifacts by criteria.

        Parameters
        ----------
        product_type : str, optional
            Filter by product type
        time_range : tuple of datetime, optional
            (start_time, end_time) filter
        radar : str, optional
            Ignored — repository is already scoped to one radar
        limit : int, optional
            Maximum results

        Returns
        -------
        list of dict
            Matching artifacts with absolute file_path resolved
        """
        df = self.catalog.query_items(
            item_type=product_type, run_id=self.run_id, order_by="scan_time ASC"
        )
        if df.empty:
            return []

        if time_range:
            t0 = time_range[0].isoformat()
            t1 = time_range[1].isoformat()
            df = df[(df["scan_time"] >= t0) & (df["scan_time"] <= t1)]

        if limit:
            df = df.head(limit)

        return [self._normalize_item(row) for _, row in df.iterrows()]

    def get_latest(
        self,
        product_type: str,
        radar: str | None = None
    ) -> dict | None:
        """Get the most recent artifact of a given type.

        Parameters
        ----------
        product_type : str
            Artifact type to query (use ProductType constants)
        radar : str, optional
            Ignored — repository is already scoped to one radar

        Returns
        -------
        dict or None
            Most recent artifact record, or None if no artifacts exist
        """
        item = self.catalog.get_latest_item(item_type=product_type, run_id=self.run_id)
        return self._normalize_item(item) if item else None

    def get_all_since(
        self,
        product_type: str,
        since_artifact_id: str | None = None,
        radar: str | None = None
    ) -> list[dict]:
        """Get all artifacts of a type created after a given artifact.

        Parameters
        ----------
        product_type : str
            Artifact type to query
        since_artifact_id : str, optional
            Return artifacts with scan_time after this artifact's scan_time.
            If None, returns all artifacts of this type.
        radar : str, optional
            Ignored — repository is already scoped to one radar

        Returns
        -------
        list of dict
            Artifacts in chronological order (oldest first)
        """
        df = self.catalog.query_items(item_type=product_type, run_id=self.run_id)
        if df.empty:
            return []

        if since_artifact_id:
            ref = self._get_artifact(since_artifact_id)
            if ref and ref.get("scan_time"):
                df = df[df["scan_time"] > ref["scan_time"]]

        df = df.sort_values("scan_time", ascending=True)
        return [self._normalize_item(row) for _, row in df.iterrows()]

    def get_artifact(self, artifact_id: str) -> dict | None:
        """Get artifact record by ID.

        Parameters
        ----------
        artifact_id : str
            Artifact ID to retrieve

        Returns
        -------
        dict or None
            Artifact record with absolute file_path, or None if not found
        """
        return self._get_artifact(artifact_id)

    def _normalize_item(self, item) -> dict:
        """Convert a RadarCatalog item row to a repository artifact dict.

        Resolves relative file_path to absolute, aliases item_id → artifact_id,
        and hoists producer from the metadata JSON for backward compatibility.
        """
        d = item.to_dict() if hasattr(item, 'to_dict') else dict(item)
        # Resolve relative path stored in catalog to absolute
        rel = d.get("file_path", "")
        if rel and not Path(rel).is_absolute():
            d["file_path"] = str(self.base_dir / self.radar / rel)
        # Alias item_id → artifact_id
        if "artifact_id" not in d:
            d["artifact_id"] = d.get("item_id", "")
        # Alias item_type → product_type
        if "product_type" not in d:
            d["product_type"] = d.get("item_type", "")
        # Hoist producer from metadata JSON for backward compatibility
        meta_raw = d.get("metadata")
        if meta_raw and isinstance(meta_raw, str):
            try:
                meta = json.loads(meta_raw)
                if "producer" not in d and "producer" in meta:
                    d["producer"] = meta["producer"]
            except (json.JSONDecodeError, TypeError):
                pass
        return d

    # =========================================================================
    # Public API: Write Operations
    # =========================================================================

    def write_netcdf(
        self,
        ds: xr.Dataset,
        product_type: str,
        scan_time: datetime,
        producer: str,
        parent_ids: list[str] | None = None,
        metadata: dict | None = None,
        filename_stem: str | None = None
    ) -> str:
        """Write xarray Dataset to NetCDF and register artifact.

        Uses atomic write (temp file + rename) for safety.

        Parameters
        ----------
        ds : xr.Dataset
            Dataset to write
        product_type : str
            Must be GRIDDED_NC or ANALYSIS_NC
        scan_time : datetime
            Scan timestamp
        producer : str
            Component name
        parent_ids : list of str, optional
            Parent artifact IDs
        metadata : dict, optional
            Additional metadata
        filename_stem : str, optional
            Base filename (without extension). Auto-generated if None.

        Returns
        -------
        str
            Registered artifact ID
        """
        # Generate output path
        output_path = self._generate_netcdf_path(
            product_type=product_type,
            scan_time=scan_time,
            filename_stem=filename_stem
        )

        # Atomic write
        self._atomic_write_netcdf(ds, output_path)

        # Register artifact
        return self.register_artifact(
            product_type=product_type,
            file_path=output_path,
            scan_time=scan_time,
            producer=producer,
            parent_ids=parent_ids,
            metadata=metadata
        )

    def write_parquet(
        self,
        df: pd.DataFrame,
        product_type: str,
        scan_time: datetime,
        producer: str,
        parent_ids: list[str] | None = None,
        metadata: dict | None = None,
        filename_stem: str | None = None
    ) -> str:
        """Write DataFrame to Parquet and register artifact.

        Parameters
        ----------
        df : pd.DataFrame
            DataFrame to write
        product_type : str
            Must be CELLS_PARQUET
        scan_time : datetime
            Scan timestamp
        producer : str
            Component name
        parent_ids : list of str, optional
            Parent artifact IDs
        metadata : dict, optional
            Additional metadata
        filename_stem : str, optional
            Base filename

        Returns
        -------
        str
            Registered artifact ID
        """
        # Generate output path
        output_path = self._generate_parquet_path(
            scan_time=scan_time,
            filename_stem=filename_stem
        )

        # Atomic write
        self._atomic_write_parquet(df, output_path)

        # Update metadata with row count
        metadata = metadata or {}
        metadata['row_count'] = len(df)

        # Register artifact
        return self.register_artifact(
            product_type=product_type,
            file_path=output_path,
            scan_time=scan_time,
            producer=producer,
            parent_ids=parent_ids,
            metadata=metadata
        )

    def write_analysis2d_parquet(
        self,
        df: pd.DataFrame,
        scan_time: datetime,
        producer: str = "processor",
        parent_ids: list[str] | None = None,
        metadata: dict | None = None
    ) -> str:
        """Write analysis DataFrame to Parquet file (one per run_id).

        This replaces the old write_sqlite_table for cells data. Data is appended
        to a single Parquet file per run at RADAR_ID/analysis/analysis2d_{run_id}.parquet.

        Parameters
        ----------
        df : pd.DataFrame
            Analysis data (cells) to write
        scan_time : datetime
            Scan timestamp
        producer : str
            Component name (default: "processor")
        parent_ids : list of str, optional
            Parent artifact IDs (e.g., gridded3d items)
        metadata : dict, optional
            Additional metadata

        Returns
        -------
        str
            Registered item ID from RadarCatalog
        """
        # Ensure required columns
        if 'radar' not in df.columns:
            df['radar'] = self.radar
        if 'run_id' not in df.columns:
            df['run_id'] = self.run_id
        if 'scan_time' not in df.columns:
            df['scan_time'] = scan_time

        # Generate parquet file path - one file per run_id
        analysis_dir = self.catalog.radar_dir / "analysis"
        analysis_dir.mkdir(parents=True, exist_ok=True)
        parquet_path = analysis_dir / f"analysis2d_{self.run_id}.parquet"

        # Append to or create parquet file
        try:
            import pyarrow as pa
            import pyarrow.parquet as pq

            # Convert to PyArrow table
            table = pa.Table.from_pandas(df)

            # If file exists, read and append; otherwise create new
            if parquet_path.exists():
                # Use pandas concat to handle schema evolution (new columns fill as NaN)
                existing_df = pq.read_table(parquet_path).to_pandas()
                combined_df = pd.concat([existing_df, df], ignore_index=True)

                # Ensure datetime columns are properly typed (fix concat type coercion)
                datetime_cols = [
                    'time', 'scan_time', 'start_time', 'end_time',
                    'time_volume_start', 'time_volume_end',
                ]
                for col in datetime_cols:
                    if col in combined_df.columns:
                        combined_df[col] = pd.to_datetime(
                            combined_df[col],
                            errors='coerce',
                            utc=True,
                        ).dt.tz_convert(None)

                table = pa.Table.from_pandas(combined_df)
                logger.debug(
                    f"Appended {len(df)} rows to {parquet_path} (schema evolution handled)"
                )

            # Write or overwrite parquet file
            pq.write_table(table, parquet_path)
            logger.debug(f"Wrote {len(table)} total rows to {parquet_path}")
            
        except ImportError:
            # Fallback to pandas (less efficient but works)
            if parquet_path.exists():
                existing_df = pd.read_parquet(parquet_path)
                df = pd.concat([existing_df, df], ignore_index=True)
                logger.debug(f"Appended {len(df)} rows to {parquet_path}")
            
            df.to_parquet(parquet_path, engine='pyarrow', index=False)
            logger.debug(f"Wrote {len(df)} total rows to {parquet_path}")

        # Register in new catalog system
        item_metadata = metadata or {}
        item_metadata['row_count'] = len(df)
        item_metadata['num_cells'] = len(df)
        item_metadata['producer'] = producer  # Store producer in metadata
        
        # Generate unique item ID
        import uuid
        item_id = str(uuid.uuid4())[:16]
        
        item_id = self.catalog.register_item(
            item_id=item_id,
            run_id=self.run_id,
            item_type="analysis2d",
            scan_time=scan_time.isoformat(),
            file_path=str(parquet_path.relative_to(self.catalog.radar_dir)),
            processing_stage="analysis",
            status="complete",
            parent_ids=parent_ids or [],
            metadata=item_metadata
        )
        
        return item_id

    def write_sqlite_table(
        self,
        df: pd.DataFrame,
        table_name: str,
        artifact_id: str,
        if_exists: str = 'append'
    ) -> None:
        """Write DataFrame to SQLite table within an existing artifact.

        Performs automatic schema migration when appending: if the DataFrame
        has columns not present in the existing table, those columns are
        added via ALTER TABLE before the insert.

        Parameters
        ----------
        df : pd.DataFrame
            Data to write
        table_name : str
            Table name
        artifact_id : str
            Existing CELLS_DB artifact ID
        if_exists : str
            Pandas to_sql behavior ('append', 'replace', 'fail')
        """
        artifact = self._get_artifact(artifact_id)

        if artifact is None:
            raise ValueError(f"Artifact not found: {artifact_id}")

        file_path = Path(artifact['file_path'])

        with sqlite3.connect(str(file_path)) as conn:
            # If appending, perform schema migration for missing columns
            if if_exists == 'append':
                self._migrate_table_schema(conn, table_name, df)

            df.to_sql(table_name, conn, if_exists=if_exists, index=False)

        logger.debug(f"Wrote {len(df)} rows to {table_name} in {artifact_id}")

    def _migrate_table_schema(
        self,
        conn: sqlite3.Connection,
        table_name: str,
        df: pd.DataFrame
    ) -> None:
        """Add missing columns to existing table before append.

        Uses the same type mapping rules as processor._create_cells_table:
        - *_x, *_y suffix → INTEGER (pixel coordinates)
        - *_lat, *_lon suffix → REAL (geographic coordinates)
        - *_json suffix → TEXT (JSON data)
        - radar_* prefix → REAL (radar measurements)
        - *_mean, *_min, *_max, *_sqkm suffix → REAL (statistics)
        - time* columns → TIMESTAMP
        - cell_label → INTEGER
        - Default → TEXT
        """
        # Check if table exists
        cursor = conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name=?",
            (table_name,)
        )
        if cursor.fetchone() is None:
            # Table doesn't exist yet, will be created by to_sql
            return

        # Get existing columns
        cursor = conn.execute(f"PRAGMA table_info('{table_name}')")
        existing_columns = {row[1] for row in cursor.fetchall()}

        # Find missing columns
        df_columns = set(df.columns)
        missing_columns = df_columns - existing_columns

        if not missing_columns:
            return

        # Add missing columns
        for col in missing_columns:
            sql_type = self._infer_sql_type(col)
            try:
                conn.execute(f'ALTER TABLE "{table_name}" ADD COLUMN "{col}" {sql_type}')
                logger.debug(f"Added column '{col}' ({sql_type}) to table '{table_name}'")
            except sqlite3.OperationalError as e:
                # Column might already exist (race condition)
                if "duplicate column name" not in str(e).lower():
                    raise

        conn.commit()
        logger.info(f"Schema migration: added {len(missing_columns)} columns to '{table_name}'")

    @staticmethod
    def _infer_sql_type(column_name: str) -> str:
        """Infer SQL type from column name using processor schema conventions.

        Type mapping rules (matching processor._create_cells_table):
        - Pixel coordinates (*_x, *_y) → INTEGER
        - Geographic coordinates (*_lat, *_lon) → REAL
        - JSON fields (*_json) → TEXT
        - Radar measurements (radar_*) → REAL
        - Statistics (*_mean, *_min, *_max, *_sqkm) → REAL
        - Timestamps (time*) → TIMESTAMP
        - Cell identifier (cell_label) → INTEGER
        - Default → TEXT
        """
        col = column_name.lower()

        # Integer types
        if col.endswith('_x') or col.endswith('_y'):
            return 'INTEGER'
        if col == 'cell_label':
            return 'INTEGER NOT NULL'

        # Real/float types
        if col.endswith('_lat') or col.endswith('_lon'):
            return 'REAL'
        if col.startswith('radar_'):
            return 'REAL'
        if col.endswith(('_mean', '_min', '_max', '_sqkm')):
            return 'REAL'
        if 'heading' in col:
            return 'REAL'
        if 'area' in col:
            return 'REAL'

        # Timestamp types
        if col.startswith('time'):
            return 'TIMESTAMP'

        # Text types
        if col.endswith('_json'):
            return 'TEXT'

        # Default to TEXT for safety
        return 'TEXT'

    def get_or_create_cells_db(
        self,
        scan_time: datetime,
        producer: str,
        parent_ids: list[str] | None = None
    ) -> str:
        """Get existing cells database or create new one.

        Parameters
        ----------
        scan_time : datetime
            Scan timestamp (used for path generation)
        producer : str
            Component name
        parent_ids : list of str, optional
            Parent artifact IDs

        Returns
        -------
        str
            Artifact ID of cells database
        """
        # Check for existing
        existing = self.query(product_type=ProductType.CELLS_DB)

        if existing:
            return existing[0]['artifact_id']

        # Create new
        output_path = self._generate_sqlite_path(scan_time)

        # Create empty database with WAL mode
        self._init_cells_db(output_path)

        return self.register_artifact(
            product_type=ProductType.CELLS_DB,
            file_path=output_path,
            scan_time=scan_time,
            producer=producer,
            parent_ids=parent_ids or [],
            metadata={}
        )

    # =========================================================================
    # Internal: Path Generation
    # =========================================================================

    def _generate_netcdf_path(
        self,
        product_type: str,
        scan_time: datetime,
        filename_stem: str | None = None
    ) -> Path:
        """Generate NetCDF output path with run_id suffix.

        Pattern: root_dir/RADAR_ID/type/YYYYMMDD/filename_{run_id}_{suffix}.nc
        """
        date_str = scan_time.strftime("%Y%m%d")
        time_str = scan_time.strftime("%H%M%S")

        if filename_stem is None:
            filename_stem = f"{self.radar}{date_str}_{time_str}"

        if product_type == ProductType.GRIDDED_NC:
            base_dir = self.output_dirs["gridnc"] / date_str
            suffix = "gridded"
        else:  # ANALYSIS_NC
            base_dir = self.output_dirs["analysis"] / date_str
            suffix = "analysis"

        base_dir.mkdir(parents=True, exist_ok=True)
        filename = f"{filename_stem}_{self.run_id}_{suffix}.nc"

        return base_dir / filename

    def _generate_parquet_path(
        self,
        scan_time: datetime,
        filename_stem: str | None = None
    ) -> Path:
        """Generate Parquet output path with run_id suffix.

        Pattern: root_dir/RADAR_ID/analysis/YYYYMMDD/filename_{run_id}_cells.parquet
        """
        date_str = scan_time.strftime("%Y%m%d")

        base_dir = self.output_dirs["analysis"] / date_str
        base_dir.mkdir(parents=True, exist_ok=True)

        if filename_stem is None:
            filename = f"{self.radar}_{self.run_id}_cells.parquet"
        else:
            filename = f"{filename_stem}_{self.run_id}.parquet"

        return base_dir / filename

    def _generate_sqlite_path(self, scan_time: datetime) -> Path:
        """Generate SQLite database path with run_id suffix.

        Pattern: root_dir/RADAR_ID/analysis/YYYYMMDD/{radar}_{run_id}_cells.db
        """
        date_str = scan_time.strftime("%Y%m%d")

        base_dir = self.output_dirs["analysis"] / date_str
        base_dir.mkdir(parents=True, exist_ok=True)

        filename = f"{self.radar}_{self.run_id}_cells.db"
        return base_dir / filename

    def generate_plot_path(
        self,
        plot_type: str,
        scan_time: datetime
    ) -> Path:
        """Generate plot output path with run_id suffix.

        Pattern: root_dir/RADAR_ID/plots/YYYYMMDD/{radar}_{plot_type}_{HHMMSS}_{run_id}.png
        """
        date_str = scan_time.strftime("%Y%m%d")
        time_str = scan_time.strftime("%H%M%S")

        base_dir = self.output_dirs["plots"] / date_str
        base_dir.mkdir(parents=True, exist_ok=True)

        filename = f"{self.radar}_{plot_type}_{time_str}_{self.run_id}.png"
        return base_dir / filename

    # =========================================================================
    # Internal: Atomic Writes
    # =========================================================================

    def _atomic_write_netcdf(self, ds: xr.Dataset, output_path: Path) -> None:
        """Write NetCDF atomically (temp file + rename)."""
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Write to temp file
        fd, temp_path = tempfile.mkstemp(suffix='.nc', dir=output_path.parent)
        os.close(fd)

        try:
            encoding = {var: {"zlib": True, "complevel": 4} for var in ds.data_vars}
            ds.to_netcdf(temp_path, encoding=encoding, engine='netcdf4')

            # Atomic rename
            shutil.move(temp_path, output_path)
            logger.debug(f"Wrote NetCDF: {output_path}")

        except Exception:
            if os.path.exists(temp_path):
                os.unlink(temp_path)
            raise

    def _atomic_write_parquet(self, df: pd.DataFrame, output_path: Path) -> None:
        """Write Parquet atomically (temp file + rename)."""
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Write to temp file
        fd, temp_path = tempfile.mkstemp(suffix='.parquet', dir=output_path.parent)
        os.close(fd)

        try:
            compression = 'snappy'
            if self.config and hasattr(self.config, 'output'):
                compression = getattr(self.config.output, 'compression', 'snappy')

            df.to_parquet(temp_path, engine='pyarrow', compression=compression, index=False)

            # Atomic rename
            shutil.move(temp_path, output_path)
            logger.debug(f"Wrote Parquet: {output_path}")

        except Exception:
            if os.path.exists(temp_path):
                os.unlink(temp_path)
            raise

    def _init_cells_db(self, db_path: Path) -> None:
        """Initialize cells database with WAL mode."""
        db_path.parent.mkdir(parents=True, exist_ok=True)

        with sqlite3.connect(str(db_path)) as conn:
            # Enable WAL mode for concurrent access
            conn.execute("PRAGMA journal_mode=WAL")
            conn.commit()

    # =========================================================================
    # Internal: Helpers
    # =========================================================================

    def _get_artifact(self, artifact_id: str) -> dict | None:
        """Get artifact record by ID from RadarCatalog."""
        row = self.catalog.get_item(artifact_id)
        return self._normalize_item(row) if row else None

    # =========================================================================
    # Lifecycle
    # =========================================================================

    def finalize_run(self, status: str = "completed") -> None:
        """Mark pipeline run as complete in the registry.

        Parameters
        ----------
        status : str
            Final status (completed, failed, cancelled)
        """
        end_time = datetime.now(UTC).isoformat()
        if self.registry:
            self.registry.update_run_status(
                run_id=self.run_id,
                status=status,
                end_time=end_time,
            )
        logger.info("Run %s finalized with status: %s", self.run_id, status)

    def close(self) -> None:
        """Close catalog connections."""
        if self.catalog:
            self.catalog.close()
        logger.debug("DataRepository closed")

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()

    # =========================================================================
    # Utility: Run ID Generation
    # =========================================================================

    @staticmethod
    def generate_run_id(radar: str) -> str:
        """Generate a run ID in YYYYMONDD-HHMM-RADAR format.

        Returns
        -------
        str
            Run identifier, e.g. ``2026MAR23-0206-KBOX``
        """
        now_local = datetime.now()
        month = now_local.strftime("%b").upper()
        return f"{now_local:%Y}{month}{now_local:%d}-{now_local:%H%M}-{radar.upper()}"
